#!/bin/bash
# Copy pstreader GUID, updating the package name
cat << END_HEADER > GUID.java
// DO NOT EDIT THIS FILE
// Automatically generated on $(date) by msgreader/extras/getGUID_java.sh
// Any changes must be made to that file.

END_HEADER
curl https://raw.githubusercontent.com/Jmcleodfoss/pstreader/master/pst/src/main/java/io/github/jmcleodfoss/GUID.java |sed '/package io.github.jmcleodfoss.pst/s/pst/msg/' >> GUID.java
