#!/bin/bash
# Process pstreader/extras/properties.csv to get properties for msgreader
curl https://raw.githubusercontent.com/Jmcleodfoss/pstreader/master/extras/properties.csv | sort -t , -k 2 | sed '
	1{
		i // DO NOT EDIT THIS FILE
		i // Automatically generated by msgreader/extras/getpropertylids.sh
		i // Any changes must be made to that file.
		i package io.github.jmcleodfoss.msg;
		i
		i class PropertyLIDs
		i {
		i \	static final java.util.HashMap<Integer, String> lids = new java.util.HashMap<Integer, String>();
		i \	static {
	}
	/^\(PidLid[^,]*\),\([^,]*\),\([^,]*\),\(.*\)$/s//\	\	lids.put(\2, "\1");/
	$ {
		i \	}
		a }
	}
	/n\/a/d
	/^PidTag/d
	' >> PropertyLIDs.java
