#!/bin/bash
# Process pstreader/extras/properties.csv to get properties for msgreader
cat << END_HEADER > PropertyLIDs.java
// DO NOT EDIT THIS FILE
// Automatically generated on $(date) by msgreader/extras/getpropertylids.sh
// Any changes must be made to that file.
package io.github.jmcleodfoss.msg;

/** Known Property Long IDs
*	@see <a href="https://github.com/Jmcleodfoss/pstreader/blob/master/extras/properties.csv">pstreader properties.pst</a>
*	@see <a href="https://github.com/Jmcleodfoss/msgreader/blob/master/extras/getpropertylids.sh">getpropertylids.sh</a>
*	@see <a href="https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/f6ab1613-aefe-447d-a49c-18217230b148">MS-OXPROPS</a>
*/

class PropertyLIDs
{
	static final java.util.HashMap<Integer, String> lids = new java.util.HashMap<Integer, String>();
	static {
END_HEADER
curl https://raw.githubusercontent.com/Jmcleodfoss/pstreader/master/extras/properties.csv | sort -t , -k 2 | sed '
	/^\(PidLid[^,]*\),\([^,]*\),\([^,]*\),\(.*\)$/s//\	\	lids.put(\2, "\1");/
	/n\/a/d
	/^PidTag/d
	' >> PropertyLIDs.java

cat << END_FOOTER >> PropertyLIDs.java
	}

	public static void main(String[] args)
	{
		java.util.Iterator<Integer> iter = PropertyLIDs.lids.keySet().iterator();
		while (iter.hasNext()) {
			Integer t = iter.next();
			System.out.printf("0x%08x: %s\n", t, PropertyLIDs.lids.get(t));
		}
	}
}
END_FOOTER
