#!/bin/bash
# Process pstreader/extras/properties.csv to get properties for msgreader
cat << END_HEADER > PropertyTags.java
// DO NOT EDIT THIS FILE
// Automatically generated on $(date) by msgreader/extras/getpropertytags.sh
// Any changes must be made to that file.
package io.github.jmcleodfoss.msg;

/** Known Property tags
*	@see <a href="https://github.com/Jmcleodfoss/pstreader/blob/master/extras/properties.csv">pstreader properties.pst</a>
*	@see <a href="https://github.com/Jmcleodfoss/msgreader/blob/master/extras/getpropertytags.sh">getpropertytags.sh</a>
*	@see <a href="https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxprops/f6ab1613-aefe-447d-a49c-18217230b148">MS-OXPROPS</a>
*/

class PropertyTags
{
	static final java.util.HashMap<Integer, String> tags = new java.util.HashMap<Integer, String>();
	static {
END_HEADER
curl https://raw.githubusercontent.com/Jmcleodfoss/pstreader/master/extras/properties.csv | sort -t , -k 2 | sed '
	/^\(PidTag[^,]*\),\([^,]*\),\([^,]*\),0x\(.*\)\r$/s//\	\	tags.put(\2\4, "\1");/
	/n\/a/d
	/^PidLid/d
	' >> PropertyTags.java

cat << END_FOOTER >> PropertyTags.java
	}
}
END_FOOTER
