#!/bin/bash
# JavaFX is bundled with Java up to Java 8.
# Set the path to JavaFX for later versions of Java as e.g.
#declare CP_JAVAFX=~/.m2/repository/org/openjfx/javafx/8.44.0/javafx.jar
declare CP_JAVAFX=

# Set the path to the java executable if not using the first instance in the path
declare JAVA_PATH="/cygdrive/c/Program Files/Java/jdk-8/bin"

# This is the classpath to the msgviewer jar
declare CP_MSGVIEWER=msgviewer/target/msgviewer-0.0-SNAPSHOT.jar

if [ "$OS" == "Windows_NT" ]
then
	declare DIR_SEP=";"
else
	declare DIR_SEP=":"
fi

if [ -n "$JAVA_PATH" ]
then
	declare JAVA_EXECUTABLE="$JAVA_PATH/java"
else
	declare JAVA_EXECUTABLE=java
fi

if [ -n "$CP_JAVAFX" ]
then
	CP_MSGVIEWER=${CP_MSGVIEWER}${DIR_SEP}${CP_JAVAFX}
fi

"$JAVA_EXECUTABLE" -cp "$CP_MSGVIEWER" io.github.jmcleodfoss.msgviewer.MsgViewer "$*"
